//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dvl
{
    [Serializable]
    public class DVLBeamMsg : Message
    {
        public const string k_RosMessageName = "dvl_msgs/DVLBeam";
        public override string RosMessageName => k_RosMessageName;

        // Transducer ID
        public long id;
        // Velocity reported by transducer
        public double velocity;
        // Distance value
        public double distance;
        // RSSI
        public double rssi;
        // NSD
        public double nsd;
        // Report if beam is locked on and providing reliable data
        public bool valid;

        public DVLBeamMsg()
        {
            this.id = 0;
            this.velocity = 0.0;
            this.distance = 0.0;
            this.rssi = 0.0;
            this.nsd = 0.0;
            this.valid = false;
        }

        public DVLBeamMsg(long id, double velocity, double distance, double rssi, double nsd, bool valid)
        {
            this.id = id;
            this.velocity = velocity;
            this.distance = distance;
            this.rssi = rssi;
            this.nsd = nsd;
            this.valid = valid;
        }

        public static DVLBeamMsg Deserialize(MessageDeserializer deserializer) => new DVLBeamMsg(deserializer);

        private DVLBeamMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.velocity);
            deserializer.Read(out this.distance);
            deserializer.Read(out this.rssi);
            deserializer.Read(out this.nsd);
            deserializer.Read(out this.valid);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.velocity);
            serializer.Write(this.distance);
            serializer.Write(this.rssi);
            serializer.Write(this.nsd);
            serializer.Write(this.valid);
        }

        public override string ToString()
        {
            return "DVLBeamMsg: " +
            "\nid: " + id.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\ndistance: " + distance.ToString() +
            "\nrssi: " + rssi.ToString() +
            "\nnsd: " + nsd.ToString() +
            "\nvalid: " + valid.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
