//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dvl
{
    [Serializable]
    public class DVLDRMsg : Message
    {
        public const string k_RosMessageName = "dvl_msgs/DVLDR";
        public override string RosMessageName => k_RosMessageName;

        // Header
        public Std.HeaderMsg header;
        // Time
        public double time;
        // Measured position [m]
        public Geometry.Vector3Msg position;
        // Estimated position
        public double pos_std;
        // IMU sensor
        public double roll;
        public double pitch;
        public double yaw;
        // Message type
        public string type;
        // Status message
        public long status;
        // Formatting of json
        public string format;

        public DVLDRMsg()
        {
            this.header = new Std.HeaderMsg();
            this.time = 0.0;
            this.position = new Geometry.Vector3Msg();
            this.pos_std = 0.0;
            this.roll = 0.0;
            this.pitch = 0.0;
            this.yaw = 0.0;
            this.type = "";
            this.status = 0;
            this.format = "";
        }

        public DVLDRMsg(Std.HeaderMsg header, double time, Geometry.Vector3Msg position, double pos_std, double roll, double pitch, double yaw, string type, long status, string format)
        {
            this.header = header;
            this.time = time;
            this.position = position;
            this.pos_std = pos_std;
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
            this.type = type;
            this.status = status;
            this.format = format;
        }

        public static DVLDRMsg Deserialize(MessageDeserializer deserializer) => new DVLDRMsg(deserializer);

        private DVLDRMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.time);
            this.position = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.pos_std);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.type);
            deserializer.Read(out this.status);
            deserializer.Read(out this.format);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.time);
            serializer.Write(this.position);
            serializer.Write(this.pos_std);
            serializer.Write(this.roll);
            serializer.Write(this.pitch);
            serializer.Write(this.yaw);
            serializer.Write(this.type);
            serializer.Write(this.status);
            serializer.Write(this.format);
        }

        public override string ToString()
        {
            return "DVLDRMsg: " +
            "\nheader: " + header.ToString() +
            "\ntime: " + time.ToString() +
            "\nposition: " + position.ToString() +
            "\npos_std: " + pos_std.ToString() +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\ntype: " + type.ToString() +
            "\nstatus: " + status.ToString() +
            "\nformat: " + format.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
