//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dvl
{
    [Serializable]
    public class DVLMsg : Message
    {
        public const string k_RosMessageName = "dvl_msgs/DVL";
        public override string RosMessageName => k_RosMessageName;

        // Header
        public Std.HeaderMsg header;
        //  Milliseconds since last velocity report (ms)
        public double time;
        // Measured velocity [m/s]
        public Geometry.Vector3Msg velocity;
        // Figure of Merit
        public double fom;
        // Covariance matrix, for the velocities. The figure of merit is calculated from this (entries in (m/s)^2)
        public double[] covariance;
        // Altitude of the sensor
        public double altitude;
        // Beams/Transducers
        public DVLBeamMsg[] beams;
        // Validity of velocity
        public bool velocity_valid;
        // Status message
        public long status;
        //  Timestamp of the surface reflection, aka 'center of ping' (Unix timestamp in microseconds)
        public long time_of_validity;
        //  Timestamp from immediately before sending of the report over TCP (Unix timestamp in microseconds)
        public long time_of_transmission;
        // Formatting of json
        public string form;

        public DVLMsg()
        {
            this.header = new Std.HeaderMsg();
            this.time = 0.0;
            this.velocity = new Geometry.Vector3Msg();
            this.fom = 0.0;
            this.covariance = new double[0];
            this.altitude = 0.0;
            this.beams = new DVLBeamMsg[0];
            this.velocity_valid = false;
            this.status = 0;
            this.time_of_validity = 0;
            this.time_of_transmission = 0;
            this.form = "";
        }

        public DVLMsg(Std.HeaderMsg header, double time, Geometry.Vector3Msg velocity, double fom, double[] covariance, double altitude, DVLBeamMsg[] beams, bool velocity_valid, long status, long time_of_validity, long time_of_transmission, string form)
        {
            this.header = header;
            this.time = time;
            this.velocity = velocity;
            this.fom = fom;
            this.covariance = covariance;
            this.altitude = altitude;
            this.beams = beams;
            this.velocity_valid = velocity_valid;
            this.status = status;
            this.time_of_validity = time_of_validity;
            this.time_of_transmission = time_of_transmission;
            this.form = form;
        }

        public static DVLMsg Deserialize(MessageDeserializer deserializer) => new DVLMsg(deserializer);

        private DVLMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.time);
            this.velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.fom);
            deserializer.Read(out this.covariance, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.altitude);
            deserializer.Read(out this.beams, DVLBeamMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.velocity_valid);
            deserializer.Read(out this.status);
            deserializer.Read(out this.time_of_validity);
            deserializer.Read(out this.time_of_transmission);
            deserializer.Read(out this.form);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.time);
            serializer.Write(this.velocity);
            serializer.Write(this.fom);
            serializer.WriteLength(this.covariance);
            serializer.Write(this.covariance);
            serializer.Write(this.altitude);
            serializer.WriteLength(this.beams);
            serializer.Write(this.beams);
            serializer.Write(this.velocity_valid);
            serializer.Write(this.status);
            serializer.Write(this.time_of_validity);
            serializer.Write(this.time_of_transmission);
            serializer.Write(this.form);
        }

        public override string ToString()
        {
            return "DVLMsg: " +
            "\nheader: " + header.ToString() +
            "\ntime: " + time.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nfom: " + fom.ToString() +
            "\ncovariance: " + System.String.Join(", ", covariance.ToList()) +
            "\naltitude: " + altitude.ToString() +
            "\nbeams: " + System.String.Join(", ", beams.ToList()) +
            "\nvelocity_valid: " + velocity_valid.ToString() +
            "\nstatus: " + status.ToString() +
            "\ntime_of_validity: " + time_of_validity.ToString() +
            "\ntime_of_transmission: " + time_of_transmission.ToString() +
            "\nform: " + form.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
