//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class ThrusterForcesMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/ThrusterForces";
        public override string RosMessageName => k_RosMessageName;

        //  force with which to spin each thruster (N)
        public double SURGE_PORT;
        public double SURGE_STAR;
        public double SWAY_BOW;
        public double SWAY_STERN;
        public double HEAVE_BOW_PORT;
        public double HEAVE_BOW_STAR;
        public double HEAVE_STERN_STAR;
        public double HEAVE_STERN_PORT;

        public ThrusterForcesMsg()
        {
            this.SURGE_PORT = 0.0;
            this.SURGE_STAR = 0.0;
            this.SWAY_BOW = 0.0;
            this.SWAY_STERN = 0.0;
            this.HEAVE_BOW_PORT = 0.0;
            this.HEAVE_BOW_STAR = 0.0;
            this.HEAVE_STERN_STAR = 0.0;
            this.HEAVE_STERN_PORT = 0.0;
        }

        public ThrusterForcesMsg(double SURGE_PORT, double SURGE_STAR, double SWAY_BOW, double SWAY_STERN, double HEAVE_BOW_PORT, double HEAVE_BOW_STAR, double HEAVE_STERN_STAR, double HEAVE_STERN_PORT)
        {
            this.SURGE_PORT = SURGE_PORT;
            this.SURGE_STAR = SURGE_STAR;
            this.SWAY_BOW = SWAY_BOW;
            this.SWAY_STERN = SWAY_STERN;
            this.HEAVE_BOW_PORT = HEAVE_BOW_PORT;
            this.HEAVE_BOW_STAR = HEAVE_BOW_STAR;
            this.HEAVE_STERN_STAR = HEAVE_STERN_STAR;
            this.HEAVE_STERN_PORT = HEAVE_STERN_PORT;
        }

        public static ThrusterForcesMsg Deserialize(MessageDeserializer deserializer) => new ThrusterForcesMsg(deserializer);

        private ThrusterForcesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.SURGE_PORT);
            deserializer.Read(out this.SURGE_STAR);
            deserializer.Read(out this.SWAY_BOW);
            deserializer.Read(out this.SWAY_STERN);
            deserializer.Read(out this.HEAVE_BOW_PORT);
            deserializer.Read(out this.HEAVE_BOW_STAR);
            deserializer.Read(out this.HEAVE_STERN_STAR);
            deserializer.Read(out this.HEAVE_STERN_PORT);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.SURGE_PORT);
            serializer.Write(this.SURGE_STAR);
            serializer.Write(this.SWAY_BOW);
            serializer.Write(this.SWAY_STERN);
            serializer.Write(this.HEAVE_BOW_PORT);
            serializer.Write(this.HEAVE_BOW_STAR);
            serializer.Write(this.HEAVE_STERN_STAR);
            serializer.Write(this.HEAVE_STERN_PORT);
        }

        public override string ToString()
        {
            return "ThrusterForcesMsg: " +
            "\nSURGE_PORT: " + SURGE_PORT.ToString() +
            "\nSURGE_STAR: " + SURGE_STAR.ToString() +
            "\nSWAY_BOW: " + SWAY_BOW.ToString() +
            "\nSWAY_STERN: " + SWAY_STERN.ToString() +
            "\nHEAVE_BOW_PORT: " + HEAVE_BOW_PORT.ToString() +
            "\nHEAVE_BOW_STAR: " + HEAVE_BOW_STAR.ToString() +
            "\nHEAVE_STERN_STAR: " + HEAVE_STERN_STAR.ToString() +
            "\nHEAVE_STERN_PORT: " + HEAVE_STERN_PORT.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
