//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class VisionObjectMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/VisionObject";
        public override string RosMessageName => k_RosMessageName;

        //  Vision Object class
        public string label;
        // pose info
        public double x;
        public double y;
        public double z;
        public double theta_z;
        // additional data field (for additional info on objects like lane marker second heading)
        public double extra_field;

        public VisionObjectMsg()
        {
            this.label = "";
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
            this.theta_z = 0.0;
            this.extra_field = 0.0;
        }

        public VisionObjectMsg(string label, double x, double y, double z, double theta_z, double extra_field)
        {
            this.label = label;
            this.x = x;
            this.y = y;
            this.z = z;
            this.theta_z = theta_z;
            this.extra_field = extra_field;
        }

        public static VisionObjectMsg Deserialize(MessageDeserializer deserializer) => new VisionObjectMsg(deserializer);

        private VisionObjectMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.label);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.theta_z);
            deserializer.Read(out this.extra_field);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.label);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.theta_z);
            serializer.Write(this.extra_field);
        }

        public override string ToString()
        {
            return "VisionObjectMsg: " +
            "\nlabel: " + label.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\ntheta_z: " + theta_z.ToString() +
            "\nextra_field: " + extra_field.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
