//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class EffortGoal : Message
    {
        public const string k_RosMessageName = "auv_msgs/Effort";
        public override string RosMessageName => k_RosMessageName;

        //  goal
        public Geometry.WrenchMsg effort;
        public Std.BoolMsg do_surge;
        public Std.BoolMsg do_sway;
        public Std.BoolMsg do_heave;
        public Std.BoolMsg do_roll;
        public Std.BoolMsg do_pitch;
        public Std.BoolMsg do_yaw;

        public EffortGoal()
        {
            this.effort = new Geometry.WrenchMsg();
            this.do_surge = new Std.BoolMsg();
            this.do_sway = new Std.BoolMsg();
            this.do_heave = new Std.BoolMsg();
            this.do_roll = new Std.BoolMsg();
            this.do_pitch = new Std.BoolMsg();
            this.do_yaw = new Std.BoolMsg();
        }

        public EffortGoal(Geometry.WrenchMsg effort, Std.BoolMsg do_surge, Std.BoolMsg do_sway, Std.BoolMsg do_heave, Std.BoolMsg do_roll, Std.BoolMsg do_pitch, Std.BoolMsg do_yaw)
        {
            this.effort = effort;
            this.do_surge = do_surge;
            this.do_sway = do_sway;
            this.do_heave = do_heave;
            this.do_roll = do_roll;
            this.do_pitch = do_pitch;
            this.do_yaw = do_yaw;
        }

        public static EffortGoal Deserialize(MessageDeserializer deserializer) => new EffortGoal(deserializer);

        private EffortGoal(MessageDeserializer deserializer)
        {
            this.effort = Geometry.WrenchMsg.Deserialize(deserializer);
            this.do_surge = Std.BoolMsg.Deserialize(deserializer);
            this.do_sway = Std.BoolMsg.Deserialize(deserializer);
            this.do_heave = Std.BoolMsg.Deserialize(deserializer);
            this.do_roll = Std.BoolMsg.Deserialize(deserializer);
            this.do_pitch = Std.BoolMsg.Deserialize(deserializer);
            this.do_yaw = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.effort);
            serializer.Write(this.do_surge);
            serializer.Write(this.do_sway);
            serializer.Write(this.do_heave);
            serializer.Write(this.do_roll);
            serializer.Write(this.do_pitch);
            serializer.Write(this.do_yaw);
        }

        public override string ToString()
        {
            return "EffortGoal: " +
            "\neffort: " + effort.ToString() +
            "\ndo_surge: " + do_surge.ToString() +
            "\ndo_sway: " + do_sway.ToString() +
            "\ndo_heave: " + do_heave.ToString() +
            "\ndo_roll: " + do_roll.ToString() +
            "\ndo_pitch: " + do_pitch.ToString() +
            "\ndo_yaw: " + do_yaw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
