//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class EffortResult : Message
    {
        public const string k_RosMessageName = "auv_msgs/Effort";
        public override string RosMessageName => k_RosMessageName;

        //  result
        public Std.BoolMsg stopped;

        public EffortResult()
        {
            this.stopped = new Std.BoolMsg();
        }

        public EffortResult(Std.BoolMsg stopped)
        {
            this.stopped = stopped;
        }

        public static EffortResult Deserialize(MessageDeserializer deserializer) => new EffortResult(deserializer);

        private EffortResult(MessageDeserializer deserializer)
        {
            this.stopped = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stopped);
        }

        public override string ToString()
        {
            return "EffortResult: " +
            "\nstopped: " + stopped.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
