//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class EffortFeedback : Message
    {
        public const string k_RosMessageName = "auv_msgs/Effort";
        public override string RosMessageName => k_RosMessageName;

        //  feedback 
        public Std.BoolMsg moving;

        public EffortFeedback()
        {
            this.moving = new Std.BoolMsg();
        }

        public EffortFeedback(Std.BoolMsg moving)
        {
            this.moving = moving;
        }

        public static EffortFeedback Deserialize(MessageDeserializer deserializer) => new EffortFeedback(deserializer);

        private EffortFeedback(MessageDeserializer deserializer)
        {
            this.moving = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.moving);
        }

        public override string ToString()
        {
            return "EffortFeedback: " +
            "\nmoving: " + moving.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
