//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class StateQuaternionFeedback : Message
    {
        public const string k_RosMessageName = "auv_msgs/StateQuaternion";
        public override string RosMessageName => k_RosMessageName;

        //  feedback 
        public Std.BoolMsg status;

        public StateQuaternionFeedback()
        {
            this.status = new Std.BoolMsg();
        }

        public StateQuaternionFeedback(Std.BoolMsg status)
        {
            this.status = status;
        }

        public static StateQuaternionFeedback Deserialize(MessageDeserializer deserializer) => new StateQuaternionFeedback(deserializer);

        private StateQuaternionFeedback(MessageDeserializer deserializer)
        {
            this.status = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "StateQuaternionFeedback: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
