//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class ObjectMapMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/ObjectMap";
        public override string RosMessageName => k_RosMessageName;

        // array containing classes detected
        public string[] label;
        // pose info
        public double[] x;
        public double[] y;
        public double[] z;
        public double[] theta_z;
        // additional data field (for additional info on objects like lane marker second heading)
        public double[] extra_field;

        public ObjectMapMsg()
        {
            this.label = new string[0];
            this.x = new double[0];
            this.y = new double[0];
            this.z = new double[0];
            this.theta_z = new double[0];
            this.extra_field = new double[0];
        }

        public ObjectMapMsg(string[] label, double[] x, double[] y, double[] z, double[] theta_z, double[] extra_field)
        {
            this.label = label;
            this.x = x;
            this.y = y;
            this.z = z;
            this.theta_z = theta_z;
            this.extra_field = extra_field;
        }

        public static ObjectMapMsg Deserialize(MessageDeserializer deserializer) => new ObjectMapMsg(deserializer);

        private ObjectMapMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.label, deserializer.ReadLength());
            deserializer.Read(out this.x, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.y, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.z, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.theta_z, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.extra_field, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.label);
            serializer.Write(this.label);
            serializer.WriteLength(this.x);
            serializer.Write(this.x);
            serializer.WriteLength(this.y);
            serializer.Write(this.y);
            serializer.WriteLength(this.z);
            serializer.Write(this.z);
            serializer.WriteLength(this.theta_z);
            serializer.Write(this.theta_z);
            serializer.WriteLength(this.extra_field);
            serializer.Write(this.extra_field);
        }

        public override string ToString()
        {
            return "ObjectMapMsg: " +
            "\nlabel: " + System.String.Join(", ", label.ToList()) +
            "\nx: " + System.String.Join(", ", x.ToList()) +
            "\ny: " + System.String.Join(", ", y.ToList()) +
            "\nz: " + System.String.Join(", ", z.ToList()) +
            "\ntheta_z: " + System.String.Join(", ", theta_z.ToList()) +
            "\nextra_field: " + System.String.Join(", ", extra_field.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
