//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class PingerTimeDifferenceMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/PingerTimeDifference";
        public override string RosMessageName => k_RosMessageName;

        public int frequency;
        public uint[] times;

        public PingerTimeDifferenceMsg()
        {
            this.frequency = 0;
            this.times = new uint[0];
        }

        public PingerTimeDifferenceMsg(int frequency, uint[] times)
        {
            this.frequency = frequency;
            this.times = times;
        }

        public static PingerTimeDifferenceMsg Deserialize(MessageDeserializer deserializer) => new PingerTimeDifferenceMsg(deserializer);

        private PingerTimeDifferenceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frequency);
            deserializer.Read(out this.times, sizeof(uint), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frequency);
            serializer.WriteLength(this.times);
            serializer.Write(this.times);
        }

        public override string ToString()
        {
            return "PingerTimeDifferenceMsg: " +
            "\nfrequency: " + frequency.ToString() +
            "\ntimes: " + System.String.Join(", ", times.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
