//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class PingerTimeDifferenceMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/PingerTimeDifference";
        public override string RosMessageName => k_RosMessageName;

        public bool is_pinger1_active;
        public bool is_pinger2_active;
        public bool is_pinger3_active;
        public bool is_pinger4_active;
        public double[] dt_pinger1;
        public double[] dt_pinger2;
        public double[] dt_pinger3;
        public double[] dt_pinger4;
        public double state_x;
        public double state_y;

        public PingerTimeDifferenceMsg()
        {
            this.is_pinger1_active = false;
            this.is_pinger2_active = false;
            this.is_pinger3_active = false;
            this.is_pinger4_active = false;
            this.dt_pinger1 = new double[0];
            this.dt_pinger2 = new double[0];
            this.dt_pinger3 = new double[0];
            this.dt_pinger4 = new double[0];
            this.state_x = 0.0;
            this.state_y = 0.0;
        }

        public PingerTimeDifferenceMsg(bool is_pinger1_active, bool is_pinger2_active, bool is_pinger3_active, bool is_pinger4_active, double[] dt_pinger1, double[] dt_pinger2, double[] dt_pinger3, double[] dt_pinger4, double state_x, double state_y)
        {
            this.is_pinger1_active = is_pinger1_active;
            this.is_pinger2_active = is_pinger2_active;
            this.is_pinger3_active = is_pinger3_active;
            this.is_pinger4_active = is_pinger4_active;
            this.dt_pinger1 = dt_pinger1;
            this.dt_pinger2 = dt_pinger2;
            this.dt_pinger3 = dt_pinger3;
            this.dt_pinger4 = dt_pinger4;
            this.state_x = state_x;
            this.state_y = state_y;
        }

        public static PingerTimeDifferenceMsg Deserialize(MessageDeserializer deserializer) => new PingerTimeDifferenceMsg(deserializer);

        private PingerTimeDifferenceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_pinger1_active);
            deserializer.Read(out this.is_pinger2_active);
            deserializer.Read(out this.is_pinger3_active);
            deserializer.Read(out this.is_pinger4_active);
            deserializer.Read(out this.dt_pinger1, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.dt_pinger2, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.dt_pinger3, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.dt_pinger4, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.state_x);
            deserializer.Read(out this.state_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_pinger1_active);
            serializer.Write(this.is_pinger2_active);
            serializer.Write(this.is_pinger3_active);
            serializer.Write(this.is_pinger4_active);
            serializer.WriteLength(this.dt_pinger1);
            serializer.Write(this.dt_pinger1);
            serializer.WriteLength(this.dt_pinger2);
            serializer.Write(this.dt_pinger2);
            serializer.WriteLength(this.dt_pinger3);
            serializer.Write(this.dt_pinger3);
            serializer.WriteLength(this.dt_pinger4);
            serializer.Write(this.dt_pinger4);
            serializer.Write(this.state_x);
            serializer.Write(this.state_y);
        }

        public override string ToString()
        {
            return "PingerTimeDifferenceMsg: " +
            "\nis_pinger1_active: " + is_pinger1_active.ToString() +
            "\nis_pinger2_active: " + is_pinger2_active.ToString() +
            "\nis_pinger3_active: " + is_pinger3_active.ToString() +
            "\nis_pinger4_active: " + is_pinger4_active.ToString() +
            "\ndt_pinger1: " + System.String.Join(", ", dt_pinger1.ToList()) +
            "\ndt_pinger2: " + System.String.Join(", ", dt_pinger2.ToList()) +
            "\ndt_pinger3: " + System.String.Join(", ", dt_pinger3.ToList()) +
            "\ndt_pinger4: " + System.String.Join(", ", dt_pinger4.ToList()) +
            "\nstate_x: " + state_x.ToString() +
            "\nstate_y: " + state_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
