//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class PingerBearingMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/PingerBearing";
        public override string RosMessageName => k_RosMessageName;

        public int frequency;
        public Geometry.Vector3Msg pinger_bearing;
        public double state_x;
        public double state_y;
        public double state_z;

        public PingerBearingMsg()
        {
            this.frequency = 0;
            this.pinger_bearing = new Geometry.Vector3Msg();
            this.state_x = 0.0;
            this.state_y = 0.0;
            this.state_z = 0.0;
        }

        public PingerBearingMsg(int frequency, Geometry.Vector3Msg pinger_bearing, double state_x, double state_y, double state_z)
        {
            this.frequency = frequency;
            this.pinger_bearing = pinger_bearing;
            this.state_x = state_x;
            this.state_y = state_y;
            this.state_z = state_z;
        }

        public static PingerBearingMsg Deserialize(MessageDeserializer deserializer) => new PingerBearingMsg(deserializer);

        private PingerBearingMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frequency);
            this.pinger_bearing = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.state_x);
            deserializer.Read(out this.state_y);
            deserializer.Read(out this.state_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frequency);
            serializer.Write(this.pinger_bearing);
            serializer.Write(this.state_x);
            serializer.Write(this.state_y);
            serializer.Write(this.state_z);
        }

        public override string ToString()
        {
            return "PingerBearingMsg: " +
            "\nfrequency: " + frequency.ToString() +
            "\npinger_bearing: " + pinger_bearing.ToString() +
            "\nstate_x: " + state_x.ToString() +
            "\nstate_y: " + state_y.ToString() +
            "\nstate_z: " + state_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
