//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class ThrusterForcesMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/ThrusterForces";
        public override string RosMessageName => k_RosMessageName;

        //  force with which to spin each thruster (N)
        //  force with which to spin each thruster (N)
        public double back_right;
        public double heave_back_right;
        public double heave_front_right;
        public double front_right;
        public double front_left;
        public double heave_front_left;
        public double heave_back_left;
        public double back_left;

        public ThrusterForcesMsg()
        {
            this.back_right = 0.0;
            this.heave_back_right = 0.0;
            this.heave_front_right = 0.0;
            this.front_right = 0.0;
            this.front_left = 0.0;
            this.heave_front_left = 0.0;
            this.heave_back_left = 0.0;
            this.back_left = 0.0;
        }

        public ThrusterForcesMsg(double back_right, double heave_back_right, double heave_front_right, double front_right, double front_left, double heave_front_left, double heave_back_left, double back_left)
        {
            this.back_right = back_right;
            this.heave_back_right = heave_back_right;
            this.heave_front_right = heave_front_right;
            this.front_right = front_right;
            this.front_left = front_left;
            this.heave_front_left = heave_front_left;
            this.heave_back_left = heave_back_left;
            this.back_left = back_left;
        }

        public static ThrusterForcesMsg Deserialize(MessageDeserializer deserializer) => new ThrusterForcesMsg(deserializer);

        private ThrusterForcesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.back_right);
            deserializer.Read(out this.heave_back_right);
            deserializer.Read(out this.heave_front_right);
            deserializer.Read(out this.front_right);
            deserializer.Read(out this.front_left);
            deserializer.Read(out this.heave_front_left);
            deserializer.Read(out this.heave_back_left);
            deserializer.Read(out this.back_left);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.back_right);
            serializer.Write(this.heave_back_right);
            serializer.Write(this.heave_front_right);
            serializer.Write(this.front_right);
            serializer.Write(this.front_left);
            serializer.Write(this.heave_front_left);
            serializer.Write(this.heave_back_left);
            serializer.Write(this.back_left);
        }

        public override string ToString()
        {
            return "ThrusterForcesMsg: " +
            "\nback_right: " + back_right.ToString() +
            "\nheave_back_right: " + heave_back_right.ToString() +
            "\nheave_front_right: " + heave_front_right.ToString() +
            "\nfront_right: " + front_right.ToString() +
            "\nfront_left: " + front_left.ToString() +
            "\nheave_front_left: " + heave_front_left.ToString() +
            "\nheave_back_left: " + heave_back_left.ToString() +
            "\nback_left: " + back_left.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
