//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class ThrusterMicrosecondsMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/ThrusterMicroseconds";
        public override string RosMessageName => k_RosMessageName;

        // Thruster definitions
        public const byte FRONT_LEFT = 0;
        public const byte FRONT_RIGHT = 1;
        public const byte BACK_LEFT = 2;
        public const byte BACK_RIGHT = 3;
        public const byte HEAVE_FRONT_LEFT = 4;
        public const byte HEAVE_FRONT_RIGHT = 5;
        public const byte HEAVE_BACK_LEFT = 6;
        public const byte HEAVE_BACK_RIGHT = 7;
        public ushort[] microseconds;

        public ThrusterMicrosecondsMsg()
        {
            this.microseconds = new ushort[8];
        }

        public ThrusterMicrosecondsMsg(ushort[] microseconds)
        {
            this.microseconds = microseconds;
        }

        public static ThrusterMicrosecondsMsg Deserialize(MessageDeserializer deserializer) => new ThrusterMicrosecondsMsg(deserializer);

        private ThrusterMicrosecondsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.microseconds, sizeof(ushort), 8);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.microseconds);
        }

        public override string ToString()
        {
            return "ThrusterMicrosecondsMsg: " +
            "\nmicroseconds: " + System.String.Join(", ", microseconds.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
