//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class ThrusterForcesMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/ThrusterForces";
        public override string RosMessageName => k_RosMessageName;

        //  force with which to spin each thruster (N)
        public double FRONT_LEFT;
        public double FRONT_RIGHT;
        public double BACK_LEFT;
        public double BACK_RIGHT;
        public double HEAVE_FRONT_LEFT;
        public double HEAVE_FRONT_RIGHT;
        public double HEAVE_BACK_LEFT;
        public double HEAVE_BACK_RIGHT;

        public ThrusterForcesMsg()
        {
            this.FRONT_LEFT = 0.0;
            this.FRONT_RIGHT = 0.0;
            this.BACK_LEFT = 0.0;
            this.BACK_RIGHT = 0.0;
            this.HEAVE_FRONT_LEFT = 0.0;
            this.HEAVE_FRONT_RIGHT = 0.0;
            this.HEAVE_BACK_LEFT = 0.0;
            this.HEAVE_BACK_RIGHT = 0.0;
        }

        public ThrusterForcesMsg(double BACK_LEFT, double FRONT_LEFT, double BACK_RIGHT, double BACK_LEFT, double HEAVE_FRONT_RIGHT, double HEAVE_FRONT_LEFT, double HEAVE_BACK_RIGHT, double HEAVE_BACK_LEFT)
        {
            this.FRONT_LEFT = FRONT_LEFT;
            this.FRONT_RIGHT = FRONT_RIGHT;
            this.BACK_LEFT = BACK_LEFT;
            this.BACK_RIGHT = BACK_RIGHT;
            this.HEAVE_FRONT_LEFT = HEAVE_FRONT_LEFT;
            this.HEAVE_FRONT_RIGHT = HEAVE_FRONT_RIGHT;
            this.HEAVE_BACK_LEFT = HEAVE_BACK_LEFT;
            this.HEAVE_BACK_RIGHT = HEAVE_BACK_RIGHT;
        }

        public static ThrusterForcesMsg Deserialize(MessageDeserializer deserializer) => new ThrusterForcesMsg(deserializer);

        private ThrusterForcesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.FRONT_LEFT);
            deserializer.Read(out this.FRONT_RIGHT);
            deserializer.Read(out this.BACK_LEFT);
            deserializer.Read(out this.BACK_RIGHT);
            deserializer.Read(out this.HEAVE_FRONT_LEFT);
            deserializer.Read(out this.HEAVE_FRONT_RIGHT);
            deserializer.Read(out this.HEAVE_BACK_LEFT);
            deserializer.Read(out this.HEAVE_BACK_RIGHT);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.FRONT_LEFT);
            serializer.Write(this.FRONT_RIGHT);
            serializer.Write(this.BACK_LEFT);
            serializer.Write(this.BACK_RIGHT);
            serializer.Write(this.HEAVE_FRONT_LEFT);
            serializer.Write(this.HEAVE_FRONT_RIGHT);
            serializer.Write(this.HEAVE_BACK_LEFT);
            serializer.Write(this.HEAVE_BACK_RIGHT);
        }

        public override string ToString()
        {
            return "ThrusterForcesMsg: " +
            "\nFRONT_LEFT: " + FRONT_LEFT.ToString() +
            "\nFRONT_RIGHT: " + FRONT_RIGHT.ToString() +
            "\nBACK_LEFT: " + BACK_LEFT.ToString() +
            "\nBACK_RIGHT: " + BACK_RIGHT.ToString() +
            "\nHEAVE_FRONT_LEFT: " + HEAVE_FRONT_LEFT.ToString() +
            "\nHEAVE_FRONT_RIGHT: " + HEAVE_FRONT_RIGHT.ToString() +
            "\nHEAVE_BACK_LEFT: " + HEAVE_BACK_LEFT.ToString() +
            "\nHEAVE_BACK_RIGHT: " + HEAVE_BACK_RIGHT.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
