//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class UnityStateMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/UnityState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.Vector3Msg position;
        public Geometry.QuaternionMsg orientation;
        public Geometry.Vector3Msg velocity;
        public Geometry.Vector3Msg angular_velocity;

        public UnityStateMsg()
        {
            this.position = new Geometry.Vector3Msg();
            this.orientation = new Geometry.QuaternionMsg();
            this.velocity = new Geometry.Vector3Msg();
            this.angular_velocity = new Geometry.Vector3Msg();
        }

        public UnityStateMsg(Geometry.Vector3Msg position, Geometry.QuaternionMsg orientation, Geometry.Vector3Msg velocity, Geometry.Vector3Msg angular_velocity)
        {
            this.position = position;
            this.orientation = orientation;
            this.velocity = velocity;
            this.angular_velocity = angular_velocity;
        }

        public static UnityStateMsg Deserialize(MessageDeserializer deserializer) => new UnityStateMsg(deserializer);

        private UnityStateMsg(MessageDeserializer deserializer)
        {
            this.position = Geometry.Vector3Msg.Deserialize(deserializer);
            this.orientation = Geometry.QuaternionMsg.Deserialize(deserializer);
            this.velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            this.angular_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.orientation);
            serializer.Write(this.velocity);
            serializer.Write(this.angular_velocity);
        }

        public override string ToString()
        {
            return "UnityStateMsg: " +
            "\nposition: " + position.ToString() +
            "\norientation: " + orientation.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nangular_velocity: " + angular_velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
