//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class UnityStateMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/UnityState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.Vector3Msg position;
        public Geometry.QuaternionMsg orientation;
        public Geometry.Vector3Msg velocity;
        public Geometry.Vector3Msg angular_velocity;
        public Geometry.Vector3Msg linear_acceleration;
        public int[] frequencies;
        public uint[] hydrophone_one_freqs;
        public uint[] hydrophone_two_freqs;
        public uint[] hydrophone_three_freqs;
        public uint[] hydrophone_four_freqs;
        public int isDVLActive;
        public int isDepthSensorActive;
        public int isIMUActive;
        public int isHydrophonesActive;

        public UnityStateMsg()
        {
            this.position = new Geometry.Vector3Msg();
            this.orientation = new Geometry.QuaternionMsg();
            this.velocity = new Geometry.Vector3Msg();
            this.angular_velocity = new Geometry.Vector3Msg();
            this.linear_acceleration = new Geometry.Vector3Msg();
            this.frequencies = new int[0];
            this.hydrophone_one_freqs = new uint[0];
            this.hydrophone_two_freqs = new uint[0];
            this.hydrophone_three_freqs = new uint[0];
            this.hydrophone_four_freqs = new uint[0];
            this.isDVLActive = 0;
            this.isDepthSensorActive = 0;
            this.isIMUActive = 0;
            this.isHydrophonesActive = 0;
        }

        public UnityStateMsg(Geometry.Vector3Msg position, Geometry.QuaternionMsg orientation, Geometry.Vector3Msg velocity, Geometry.Vector3Msg angular_velocity, Geometry.Vector3Msg linear_acceleration, int[] frequencies, uint[] hydrophone_one_freqs, uint[] hydrophone_two_freqs, uint[] hydrophone_three_freqs, uint[] hydrophone_four_freqs, int isDVLActive, int isDepthSensorActive, int isIMUActive, int isHydrophonesActive)
        {
            this.position = position;
            this.orientation = orientation;
            this.velocity = velocity;
            this.angular_velocity = angular_velocity;
            this.linear_acceleration = linear_acceleration;
            this.frequencies = frequencies;
            this.hydrophone_one_freqs = hydrophone_one_freqs;
            this.hydrophone_two_freqs = hydrophone_two_freqs;
            this.hydrophone_three_freqs = hydrophone_three_freqs;
            this.hydrophone_four_freqs = hydrophone_four_freqs;
            this.isDVLActive = isDVLActive;
            this.isDepthSensorActive = isDepthSensorActive;
            this.isIMUActive = isIMUActive;
            this.isHydrophonesActive = isHydrophonesActive;
        }

        public static UnityStateMsg Deserialize(MessageDeserializer deserializer) => new UnityStateMsg(deserializer);

        private UnityStateMsg(MessageDeserializer deserializer)
        {
            this.position = Geometry.Vector3Msg.Deserialize(deserializer);
            this.orientation = Geometry.QuaternionMsg.Deserialize(deserializer);
            this.velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            this.angular_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            this.linear_acceleration = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.frequencies, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.hydrophone_one_freqs, sizeof(uint), deserializer.ReadLength());
            deserializer.Read(out this.hydrophone_two_freqs, sizeof(uint), deserializer.ReadLength());
            deserializer.Read(out this.hydrophone_three_freqs, sizeof(uint), deserializer.ReadLength());
            deserializer.Read(out this.hydrophone_four_freqs, sizeof(uint), deserializer.ReadLength());
            deserializer.Read(out this.isDVLActive);
            deserializer.Read(out this.isDepthSensorActive);
            deserializer.Read(out this.isIMUActive);
            deserializer.Read(out this.isHydrophonesActive);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.orientation);
            serializer.Write(this.velocity);
            serializer.Write(this.angular_velocity);
            serializer.Write(this.linear_acceleration);
            serializer.WriteLength(this.frequencies);
            serializer.Write(this.frequencies);
            serializer.WriteLength(this.hydrophone_one_freqs);
            serializer.Write(this.hydrophone_one_freqs);
            serializer.WriteLength(this.hydrophone_two_freqs);
            serializer.Write(this.hydrophone_two_freqs);
            serializer.WriteLength(this.hydrophone_three_freqs);
            serializer.Write(this.hydrophone_three_freqs);
            serializer.WriteLength(this.hydrophone_four_freqs);
            serializer.Write(this.hydrophone_four_freqs);
            serializer.Write(this.isDVLActive);
            serializer.Write(this.isDepthSensorActive);
            serializer.Write(this.isIMUActive);
            serializer.Write(this.isHydrophonesActive);
        }

        public override string ToString()
        {
            return "UnityStateMsg: " +
            "\nposition: " + position.ToString() +
            "\norientation: " + orientation.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nangular_velocity: " + angular_velocity.ToString() +
            "\nlinear_acceleration: " + linear_acceleration.ToString() +
            "\nfrequencies: " + System.String.Join(", ", frequencies.ToList()) +
            "\nhydrophone_one_freqs: " + System.String.Join(", ", hydrophone_one_freqs.ToList()) +
            "\nhydrophone_two_freqs: " + System.String.Join(", ", hydrophone_two_freqs.ToList()) +
            "\nhydrophone_three_freqs: " + System.String.Join(", ", hydrophone_three_freqs.ToList()) +
            "\nhydrophone_four_freqs: " + System.String.Join(", ", hydrophone_four_freqs.ToList()) +
            "\nisDVLActive: " + isDVLActive.ToString() +
            "\nisDepthSensorActive: " + isDepthSensorActive.ToString() +
            "\nisIMUActive: " + isIMUActive.ToString() +
            "\nisHydrophonesActive: " + isHydrophonesActive.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
