//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class VisionDetectionFrameMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/VisionDetectionFrame";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geometry.PoseStampedMsg auv_pose;
        public VisionDetectionMsg[] detections;

        public VisionDetectionFrameMsg()
        {
            this.header = new Std.HeaderMsg();
            this.auv_pose = new Geometry.PoseStampedMsg();
            this.detections = new VisionDetectionMsg[0];
        }

        public VisionDetectionFrameMsg(Std.HeaderMsg header, Geometry.PoseStampedMsg auv_pose, VisionDetectionMsg[] detections)
        {
            this.header = header;
            this.auv_pose = auv_pose;
            this.detections = detections;
        }

        public static VisionDetectionFrameMsg Deserialize(MessageDeserializer deserializer) => new VisionDetectionFrameMsg(deserializer);

        private VisionDetectionFrameMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.auv_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.detections, VisionDetectionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.auv_pose);
            serializer.WriteLength(this.detections);
            serializer.Write(this.detections);
        }

        public override string ToString()
        {
            return "VisionDetectionFrameMsg: " +
            "\nheader: " + header.ToString() +
            "\nauv_pose: " + auv_pose.ToString() +
            "\ndetections: " + System.String.Join(", ", detections.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
