//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class VisionObjectMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/VisionObject";
        public override string RosMessageName => k_RosMessageName;

        //  Standard Header (CRITICAL for TF/Time sync)
        public Std.HeaderMsg header;
        //  Logic Data
        public string label;
        //  Semantic Class (e.g., "gate", "buoy")
        public int id;
        //  Unique tracking ID (e.g., Tracker ID 1)
        //  Standard Geometry
        //  Replaces x, y, z, theta_z. Allows direct use with TF2 and Planner
        public Geometry.PoseMsg pose;
        //  Domain Specifics
        public bool has_orientation;
        //  True if orientation was explicitly calculated
        public Geometry.Vector3Msg size;
        //  Dimensions (x, y, z)
        public double confidence;
        //  0.0 to 1.0

        public VisionObjectMsg()
        {
            this.header = new Std.HeaderMsg();
            this.label = "";
            this.id = 0;
            this.pose = new Geometry.PoseMsg();
            this.has_orientation = false;
            this.size = new Geometry.Vector3Msg();
            this.confidence = 0.0;
        }

        public VisionObjectMsg(Std.HeaderMsg header, string label, int id, Geometry.PoseMsg pose, bool has_orientation, Geometry.Vector3Msg size, double confidence)
        {
            this.header = header;
            this.label = label;
            this.id = id;
            this.pose = pose;
            this.has_orientation = has_orientation;
            this.size = size;
            this.confidence = confidence;
        }

        public static VisionObjectMsg Deserialize(MessageDeserializer deserializer) => new VisionObjectMsg(deserializer);

        private VisionObjectMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.label);
            deserializer.Read(out this.id);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.has_orientation);
            this.size = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.confidence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.label);
            serializer.Write(this.id);
            serializer.Write(this.pose);
            serializer.Write(this.has_orientation);
            serializer.Write(this.size);
            serializer.Write(this.confidence);
        }

        public override string ToString()
        {
            return "VisionObjectMsg: " +
            "\nheader: " + header.ToString() +
            "\nlabel: " + label.ToString() +
            "\nid: " + id.ToString() +
            "\npose: " + pose.ToString() +
            "\nhas_orientation: " + has_orientation.ToString() +
            "\nsize: " + size.ToString() +
            "\nconfidence: " + confidence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
