//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Auv
{
    [Serializable]
    public class VisionDetectionMsg : Message
    {
        public const string k_RosMessageName = "auv_msgs/VisionDetection";
        public override string RosMessageName => k_RosMessageName;

        public string label;
        public double confidence;
        public Geometry.PoseWithCovarianceMsg pose_camera;
        public double bbox_center_x;
        public double bbox_center_y;
        public double bbox_size_x;
        public double bbox_size_y;

        public VisionDetectionMsg()
        {
            this.label = "";
            this.confidence = 0.0;
            this.pose_camera = new Geometry.PoseWithCovarianceMsg();
            this.bbox_center_x = 0.0;
            this.bbox_center_y = 0.0;
            this.bbox_size_x = 0.0;
            this.bbox_size_y = 0.0;
        }

        public VisionDetectionMsg(string label, double confidence, Geometry.PoseWithCovarianceMsg pose_camera, double bbox_center_x, double bbox_center_y, double bbox_size_x, double bbox_size_y)
        {
            this.label = label;
            this.confidence = confidence;
            this.pose_camera = pose_camera;
            this.bbox_center_x = bbox_center_x;
            this.bbox_center_y = bbox_center_y;
            this.bbox_size_x = bbox_size_x;
            this.bbox_size_y = bbox_size_y;
        }

        public static VisionDetectionMsg Deserialize(MessageDeserializer deserializer) => new VisionDetectionMsg(deserializer);

        private VisionDetectionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.label);
            deserializer.Read(out this.confidence);
            this.pose_camera = Geometry.PoseWithCovarianceMsg.Deserialize(deserializer);
            deserializer.Read(out this.bbox_center_x);
            deserializer.Read(out this.bbox_center_y);
            deserializer.Read(out this.bbox_size_x);
            deserializer.Read(out this.bbox_size_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.label);
            serializer.Write(this.confidence);
            serializer.Write(this.pose_camera);
            serializer.Write(this.bbox_center_x);
            serializer.Write(this.bbox_center_y);
            serializer.Write(this.bbox_size_x);
            serializer.Write(this.bbox_size_y);
        }

        public override string ToString()
        {
            return "VisionDetectionMsg: " +
            "\nlabel: " + label.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\npose_camera: " + pose_camera.ToString() +
            "\nbbox_center_x: " + bbox_center_x.ToString() +
            "\nbbox_center_y: " + bbox_center_y.ToString() +
            "\nbbox_size_x: " + bbox_size_x.ToString() +
            "\nbbox_size_y: " + bbox_size_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
